/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/renderer/index.html', './src/renderer/src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': 'var(--color-on-error-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'error-container': 'var(--color-error-container)',
        'surface-dim': 'var(--color-surface-dim)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        surface: 'var(--color-surface)',
        'surface-container': 'var(--color-surface-container)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface': 'var(--color-on-surface)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'on-primary': 'var(--color-on-primary)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'tertiary-container': 'var(--color-tertiary-container)',
        tertiary: 'var(--color-tertiary)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'surface-tint': 'var(--color-surface-tint)',
        error: 'var(--color-error)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'primary-container': 'var(--color-primary-container)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'surface-variant': 'var(--color-surface-variant)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        secondary: 'var(--color-secondary)',
        'on-error': 'var(--color-on-error)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        outline: 'var(--color-outline)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        primary: 'var(--color-primary)',
        'outline-variant': 'var(--color-outline-variant)',
        'on-background': 'var(--color-on-background)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        background: 'var(--color-background)',
        base: 'var(--color-base)',
        accent: 'var(--color-primary-container)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '24px',
        xl: '32px',
        unit: '4px',
        gutter: '1px',
        md: '16px',
        'panel-width': '400px',
        sm: '8px',
        'sidebar-width': '260px',
        xs: '4px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'code-base': ['JetBrains Mono', 'monospace'],
        'label-caps': ['Inter', 'system-ui', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Inter', 'system-ui', 'sans-serif'],
        'display-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-base': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        'code-base': ['13px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'code-sm': ['11px', { lineHeight: '1.4', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-base': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      animation: {
        'pulse-subtle': 'pulse-subtle 1.5s ease-in-out infinite',
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.2s ease-out',
        'pulse-dot': 'pulse-dot 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-dot': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.4' },
        },
      },
    },
  },
  plugins: [],
}
